# Generated by Django 2.2 on 2019-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
