# Generated by Django 2.2 on 2019-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='news',
            name='raw_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
