# Generated by Django 2.2 on 2019-04-14 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190414_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='raw_content',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
