# Generated by Django 2.1.7 on 2019-04-01 16:27

import common.enum.access
import common.enum.role
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='access',
            name='access_type',
            field=models.CharField(choices=[(common.enum.access.SystemValidAccess('ADMIN_ACCESS'), 'ADMIN_ACCESS'), (common.enum.access.SystemValidAccess('CREATE_CUSTOMER_SERVICE_STAFF'), 'CREATE_CUSTOMER_SERVICE_STAFF'), (common.enum.access.SystemValidAccess('DELETE_CUSTOMER_SERVICE_STAFF'), 'DELETE_CUSTOMER_SERVICE_STAFF'), (common.enum.access.SystemValidAccess('MODIFY_CUSTOMER_SERVICE_STAFF'), 'MODIFY_CUSTOMER_SERVICE_STAFF'), (common.enum.access.SystemValidAccess('QUERY_CUSTOMER_SERVICE_STAFF'), 'QUERY_CUSTOMER_SERVICE_STAFF'), (common.enum.access.SystemValidAccess('CREATE_CUSTOMER'), 'CREATE_CUSTOMER'), (common.enum.access.SystemValidAccess('MODIFY_CUSTOMER'), 'MODIFY_CUSTOMER'), (common.enum.access.SystemValidAccess('QUERY_CUSTOMER'), 'QUERY_CUSTOMER'), (common.enum.access.SystemValidAccess('CUSTOMER_ACCESS_LEVEL_1'), 'CUSTOMER_ACCESS_LEVEL_1'), (common.enum.access.SystemValidAccess('CUSTOMER_ACCESS_LEVEL_2'), 'CUSTOMER_ACCESS_LEVEL_2'), (common.enum.access.SystemValidAccess('CUSTOMER_ACCESS_LEVEL_3'), 'CUSTOMER_ACCESS_LEVEL_3'), (common.enum.access.SystemValidAccess('CUSTOMER_ACCESS_LEVEL_4'), 'CUSTOMER_ACCESS_LEVEL_4'), (common.enum.access.SystemValidAccess('NO_ACCESS'), 'NO_ACCESS')], default=common.enum.access.SystemValidAccess('NO_ACCESS'), max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[(common.enum.role.SystemValidRole('ADMIN'), 'ADMIN'), (common.enum.role.SystemValidRole('MANAGER'), 'MANAGER'), (common.enum.role.SystemValidRole('CUSTOMER_SERVICE_STUFF'), 'CUSTOMER_SERVICE_STUFF'), (common.enum.role.SystemValidRole('CUSTOMER_LEVLE_1'), 'CUSTOMER_LEVLE_1'), (common.enum.role.SystemValidRole('CUSTOMER_LEVLE_2'), 'CUSTOMER_LEVLE_2'), (common.enum.role.SystemValidRole('CUSTOMER_LEVLE_3'), 'CUSTOMER_LEVLE_3'), (common.enum.role.SystemValidRole('CUSTOMER_LEVLE_4'), 'CUSTOMER_LEVLE_4'), (common.enum.role.SystemValidRole('VISITOR'), 'VISITOR')], default='VISITOR', max_length=50),
        ),
    ]
