from enum import Enum


class SystemValidAccess(Enum):
    # Administration
    ADMIN_ACCESS = 'ADMIN_ACCESS'

    # Manager
    CREATE_CUSTOMER_SERVICE_STAFF = 'CREATE_CUSTOMER_SERVICE_STAFF'
    DELETE_CUSTOMER_SERVICE_STAFF = 'DELETE_CUSTOMER_SERVICE_STAFF'
    MODIFY_CUSTOMER_SERVICE_STAFF = 'MODIFY_CUSTOMER_SERVICE_STAFF'
    QUERY_CUSTOMER_SERVICE_STAFF = 'QUERY_CUSTOMER_SERVICE_STAFF'

    # Customer service staff
    CREATE_CUSTOMER = 'CREATE_CUSTOMER'
    # DELETE_CUSTOMER = 'DELETE_CUSTOMER'
    MODIFY_CUSTOMER = 'MODIFY_CUSTOMER'
    QUERY_CUSTOMER = 'QUERY_CUSTOMER'

    # Customer
    CUSTOMER_ACCESS_LEVEL_1 = 'CUSTOMER_ACCESS_LEVEL_1'
    CUSTOMER_ACCESS_LEVEL_2 = 'CUSTOMER_ACCESS_LEVEL_2'
    CUSTOMER_ACCESS_LEVEL_3 = 'CUSTOMER_ACCESS_LEVEL_3'
    CUSTOMER_ACCESS_LEVEL_4 = 'CUSTOMER_ACCESS_LEVEL_4'
    NO_ACCESS = 'NO_ACCESS'
