from enum import Enum


class SystemValidRole(Enum):
    ADMIN = 'ADMIN'
    MANAGER = 'MANAGER'
    CUSTOMER_SERVICE_STAFF = 'CUSTOMER_SERVICE_STUFF'
    CUSTOMER_LEVEL_1 = 'CUSTOMER_LEVLE_1'
    CUSTOMER_LEVEL_2 = 'CUSTOMER_LEVLE_2'
    CUSTOMER_LEVEL_3 = 'CUSTOMER_LEVLE_3'
    CUSTOMER_LEVEL_4 = 'CUSTOMER_LEVLE_4'
    VISITOR = 'VISITOR'
