# Generated by Django 2.1.7 on 2019-04-07 18:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import souq.models_migrate.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('img_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, unique=True)),
                ('plantform', models.CharField(max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('ean_code', models.CharField(max_length=50)),
                ('trace_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='souq.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MCategory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='MDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('img_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000)),
                ('plantform', models.CharField(max_length=20)),
                ('category', djongo.models.fields.GenericObjectIdField()),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('ean_code', models.CharField(max_length=50)),
                ('trace_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('seller', djongo.models.fields.GenericObjectIdField()),
                ('detail', djongo.models.fields.ArrayModelField(model_container=souq.models_migrate.item.MDetail)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='MSeller',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='souq.Seller'),
        ),
        migrations.AddField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souq.Item'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['link'], name='souq_item_link_d2236c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['ean_code'], name='souq_item_ean_cod_5ae6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='souq_item_name_797c16_idx'),
        ),
    ]
