# Generated by Django 2.1.7 on 2019-03-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('classification', models.CharField(max_length=50)),
                ('link', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('time', models.DateField(db_index=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SouqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(db_index=True, max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souq.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souq.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souq.SouqItem'),
        ),
    ]
