# Generated by Django 2.2 on 2019-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='identify',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['identify'], name='souq_detail_identif_730880_idx'),
        ),
    ]
