# Generated by Django 2.1.7 on 2019-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0002_auto_20190314_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souqitem',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
