# Generated by Django 2.2 on 2019-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0003_detail_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='buybox',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdetail',
            name='buybox',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdetail',
            name='sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitem',
            name='unit_id',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
