# Generated by Django 2.1.7 on 2019-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0003_auto_20190314_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souqitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
