# Generated by Django 2.2 on 2019-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0004_auto_20190419_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_id',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['unit_id'], name='souq_item_unit_id_3f552b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['trace_id'], name='souq_item_trace_i_828f89_idx'),
        ),
    ]
