# Generated by Django 2.2 on 2019-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0005_auto_20190419_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('souq.item',),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
