# Generated by Django 2.2 on 2019-04-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0005_auto_20190419_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('souq.item',),
        ),
    ]
