# Generated by Django 2.1.7 on 2019-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0005_auto_20190314_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souqitem',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
