# Generated by Django 2.2 on 2019-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0006_auto_20190420_1650'),
        ('souq', '0006_hotitem'),
    ]

    operations = [
    ]
