# Generated by Django 2.1 on 2019-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0008_singleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('souq.category',),
        ),
        migrations.CreateModel(
            name='SingleSeller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('souq.seller',),
        ),
    ]
